<nav role="navigation">
	<ul id="main-menu">
		<!-- TODO: <li><a href="{{#_icp}}popular{{/_icp}}">Populært</a>-->
		<li><a href="{{#_icp}}person/index{{/_icp}}">Person</a>
		<li><a href="{{#_icp}}series/index{{/_icp}}">Serie</a>
		<li><a href="{{#_icp}}location/index{{/_icp}}">Sted</a>
		<!-- TODO: <li><a href="{{#_icp}}time/index{{/_icp}}">Tid</a>-->
		{{#_user}}
		<li><a href="{{#_icp}}tools{{/_icp}}">🛠 Verktøy</a>
		{{/_user}}
	</ul>
</nav>
