{{% ACCESS editor }}
{{% BLOCKS }}
{{< layout }}
{{$ title }}Mapper med nytt innhold{{/ title }}

{{$ content}}


<script defer type="text/javascript" src="js/manage-content-fresh-dirs.js"></script>


<h1>Mapper med nytt innhold</h1>

<table class="directories fixed full-width">
	<thead>
		<tr>
			<th>Mappe</th>
			<th style="width: 3em">Filer</th>
			<th style="width: 3em"></th>
		</tr>
	</thead>
	<tbody class="striped">
		<!-- ko template: { name: 'row-tmpl', foreach: directories} -->
		<!-- /ko -->
	</tbody>
	<tfoot>
		<tr>
			<td></td>
			<td data-bind="text: total"></td>
		</tr>
	</tfoot>
</table>


{{> waiting }}


<script type="text/html" id="row-tmpl">
	<tr>
		<td data-bind="text: title"></td>
		<td data-bind="text: count"></td>
		<td>
			<form action="{{PATH}}/../fresh-content">
				<input type="hidden" name="path" data-bind="value: path">
				<button>→</button>
			</form>
		</td>
	</tr>
</script>


{{/ content}}
{{/ layout }}
