<?php

return (object) [
	'global' => [
		'https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css',
		'https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300i|Open+Sans:400,400italic,700',
		'https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.css',
		'https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.min.css',
		'theme/layout.css',
		],
];
